name: Build
on: 
    push:
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
          with:
            java-version: 1.8
      - name: Build the app
        run: ./gradlew assembleRelease
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with: release apk
        path: anode-co/AnodeVPN-android/app-release.apk