on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'keystore/your_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          
      - name: Git pull tags
        run: git fetch --tags    
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build prod
        run: ./gradlew app:bundleRelease
        env:
          PLAYSTORE_BUILD: true
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/
      
      #Publish the AAB to Play store    
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.18
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: co.anode.anodium.playstore
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
          inAppUpdatePriority: 3
          changesNotSentForReview: true
          #userFraction: 0.99 #for inProgress status
          whatsNewDirectory: /home/runner/work/AnodeVPN-android/AnodeVPN-android/whatsnew
      # - name: Debug with tmate on failure
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3