on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        
  push:
    tags:
      - anodevpn-*.*.*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Install packages
        run: sudo apt-get install jq bash curl

      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: ${{ env.RELEASE_NAME }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # See https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      #Building APK
      - name: Build APK with Gradle
        run: ./gradlew assembleRelease
        env:
          CI: 'true'
          ANODE_CONFIDENTIAL_alias: ${{ secrets.ANODE_CONFIDENTIAL_ALIAS }}
          ANODE_CONFIDENTIAL_password0: ${{ secrets.ANODE_CONFIDENTIAL_PASSWORD0 }}
          ANODE_CONFIDENTIAL_password1: ${{ secrets.ANODE_CONFIDENTIAL_PASSWORD1 }}
      
      #Build signed AAB for Play store
      - name: Build bundle (AAB) with Gradle
        run: ./gradlew bundleRelease
        env:
          CI: 'true'
          ANODE_CONFIDENTIAL_alias: ${{ secrets.ANODE_CONFIDENTIAL_ALIAS }}
          ANODE_CONFIDENTIAL_password0: ${{ secrets.ANODE_CONFIDENTIAL_PASSWORD0 }}
          ANODE_CONFIDENTIAL_password1: ${{ secrets.ANODE_CONFIDENTIAL_PASSWORD1 }}
      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle#caching-dependencies
      - name: Clean up Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -fr ~/.gradle/caches/gc.properties
          rm -fr ~/.gradle/caches/*/plugin-resolution/

      - uses: actions/upload-artifact@main
        with:
          name: release apk
          path: /home/runner/work/AnodeVPN-android/AnodeVPN-android/app/build/outputs/apk/release/app-release.apk

      - name: Publish release
        run: /bin/bash -c 'source ./tools/publish.sh'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANODE_APIKEY: ${{ secrets.ANODE_APIKEY }}
          
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.18
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: co.anode.anodium
          releaseFiles: /home/runner/work/AnodeVPN-android/AnodeVPN-android/app/build/outputs/apk/release/app-release.aab
          track: internal
          status: inProgress
          inAppUpdatePriority: 3
          userFraction: 0.99
          whatsNewDirectory: /home/runner/work/AnodeVPN-android/AnodeVPN-android/whatsnew
